alias: 11 - Door Sensor
description: Controls alarm based on rear door status and bypass button.
triggers:
  - event_type: shelly.click
    event_data:
      device: shellybutton1-786519B128BB
      click_type: single
    id: button_pressed
    trigger: event
  - entity_id: binary_sensor.rear_door_sensor
    to: "on"
    for:
      seconds: 1
    id: door_opened
    trigger: state
  - entity_id: binary_sensor.rear_door_sensor
    to: "off"
    for:
      seconds: 1
    id: door_closed
    trigger: state
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: button_pressed
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: input_boolean.alarm_bypass
                    state: "off"
                sequence:
                  - target:
                      entity_id: input_boolean.alarm_bypass
                    action: input_boolean.turn_on
                    data: {}
                  - target:
                      entity_id: switch.shellyplus1_100111111c_switch_0
                    action: switch.turn_on
                    data: {}
              - conditions:
                  - condition: state
                    entity_id: input_boolean.alarm_bypass
                    state: "on"
                sequence:
                  - target:
                      entity_id: input_boolean.alarm_bypass
                    action: input_boolean.turn_off
                    data: {}
                  - target:
                      entity_id: switch.shellyplus1_10061c111111_switch_0
                    action: switch.turn_off
                    data: {}
      - conditions:
          - condition: trigger
            id: door_opened
          - condition: state
            entity_id: input_boolean.alarm_bypass
            state: "off"
        sequence:
          - target:
              entity_id: switch.shellyplus1_c4d8d11111_switch_0
            action: switch.turn_on
            data: {}
      - conditions:
          - condition: trigger
            id: door_closed
        sequence:
          - target:
              entity_id:
                - switch.shellyplus1_10061111111c_switch_0
                - switch.shellyplus1_c4d8d211111_switch_0
            action: switch.turn_off
            data: {}
          - target:
              entity_id: input_boolean.alarm_bypass
            action: input_boolean.turn_off
            data: {}
mode: queued
max: 5
